import jsPDF from 'jspdf';

interface StudentPDFData {
    studentName: string;
    sessionName: string;
    sessionDate: string;
    activityTime: number;
    participatedPages: number;
    feedbackCount: number;
    pageParticipation: {
        pageNumber: number;
        writingTime: number;
        strokeCount: number;
        firstWriteTime: string;
        lastWriteTime: string;
    }[];
}

/**
 * 학생 리포트 PDF 생성
 * @param data 학생 데이터
 * @returns Promise<void>
 */
export const generateStudentReportPDF = async (data: StudentPDFData): Promise<void> => {
    // A4 세로 방향
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;

    // 한글 폰트 문제로 인해 기본 폰트 사용 (한글은 이미지로 변환하거나 폰트 임베딩 필요)
    // 여기서는 간단히 ASCII 문자로 대체

    // ===== 헤더 =====
    doc.setFontSize(20);
    doc.text('Student Report', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    // ===== 학생 정보 =====
    doc.setFontSize(12);
    doc.text(`Student: ${data.studentName}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Session: ${data.sessionName}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Date: ${data.sessionDate}`, 20, yPosition);
    yPosition += 15;

    // ===== 요약 정보 =====
    doc.setFontSize(14);
    doc.text('Summary', 20, yPosition);
    yPosition += 10;

    doc.setFontSize(11);
    doc.text(`Total Activity Time: ${data.activityTime} min`, 25, yPosition);
    yPosition += 7;
    doc.text(`Participated Pages: ${data.participatedPages}`, 25, yPosition);
    yPosition += 7;
    doc.text(`Received Feedback: ${data.feedbackCount}`, 25, yPosition);
    yPosition += 7;

    const avgStrokes = Math.round(
        data.pageParticipation.reduce((sum, p) => sum + p.strokeCount, 0) /
        data.pageParticipation.length
    );
    doc.text(`Average Strokes per Page: ${avgStrokes}`, 25, yPosition);
    yPosition += 15;

    // ===== 페이지별 참여 표 =====
    doc.setFontSize(14);
    doc.text('Page Participation', 20, yPosition);
    yPosition += 10;

    // 테이블 헤더
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    const tableStartY = yPosition;
    const col1X = 20;
    const col2X = 50;
    const col3X = 80;
    const col4X = 110;
    const col5X = 140;

    doc.text('Page', col1X, tableStartY);
    doc.text('Time', col2X, tableStartY);
    doc.text('Strokes', col3X, tableStartY);
    doc.text('First', col4X, tableStartY);
    doc.text('Last', col5X, tableStartY);
    yPosition += 7;

    // 구분선
    doc.line(20, yPosition - 2, pageWidth - 20, yPosition - 2);

    // 테이블 데이터
    doc.setFont('helvetica', 'normal');
    for (const page of data.pageParticipation) {
        // 페이지 넘김 체크
        if (yPosition > pageHeight - 30) {
            doc.addPage();
            yPosition = 20;

            // 새 페이지에 헤더 다시 그리기
            doc.setFont('helvetica', 'bold');
            doc.text('Page', col1X, yPosition);
            doc.text('Time', col2X, yPosition);
            doc.text('Strokes', col3X, yPosition);
            doc.text('First', col4X, yPosition);
            doc.text('Last', col5X, yPosition);
            yPosition += 7;
            doc.line(20, yPosition - 2, pageWidth - 20, yPosition - 2);
            doc.setFont('helvetica', 'normal');
        }

        const timeInMin = Math.floor(page.writingTime / 60);
        const timeInSec = page.writingTime % 60;
        const timeStr = `${timeInMin}:${timeInSec.toString().padStart(2, '0')}`;

        doc.text(`Page ${page.pageNumber}`, col1X, yPosition);
        doc.text(timeStr, col2X, yPosition);
        doc.text(`${page.strokeCount}`, col3X, yPosition);
        doc.text(page.firstWriteTime, col4X, yPosition);
        doc.text(page.lastWriteTime, col5X, yPosition);
        yPosition += 6;
    }

    // 합계 행
    yPosition += 3;
    doc.line(20, yPosition - 2, pageWidth - 20, yPosition - 2);
    doc.setFont('helvetica', 'bold');

    const totalTime = data.pageParticipation.reduce((sum, p) => sum + p.writingTime, 0);
    const totalMin = Math.floor(totalTime / 60);
    const totalSec = totalTime % 60;
    const totalTimeStr = `${totalMin}:${totalSec.toString().padStart(2, '0')}`;

    const totalStrokes = data.pageParticipation.reduce((sum, p) => sum + p.strokeCount, 0);

    doc.text('Total', col1X, yPosition);
    doc.text(totalTimeStr, col2X, yPosition);
    doc.text(`${totalStrokes}`, col3X, yPosition);

    // ===== 푸터 =====
    yPosition = pageHeight - 15;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by NeoCast', pageWidth / 2, yPosition, { align: 'center' });
    doc.text(new Date().toLocaleString('ko-KR'), pageWidth / 2, yPosition + 5, { align: 'center' });

    // PDF 다운로드
    const fileName = `${data.studentName}_${data.sessionDate}_Report.pdf`;
    doc.save(fileName);
};

/**
 * 시간 포맷팅 (초 → MM:SS)
 */
export const formatTime = (seconds: number): string => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
};
